
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author alexandrezamberlan
 */
public class ServidorJogador1 extends javax.swing.JFrame {

    /**
     * Creates new form ServidorJogador1
     */
    public ServidorJogador1() {
        initComponents();

        new Thread() {
            @Override
            public void run() {
                try {
                    System.out.println("Servidor esperando o cliente conectar-se...porta 12345");
                    servidor = new ServerSocket(12345);

                    socket_jogador2 = servidor.accept();
                    // o método accept() bloqueia a execução até que
                    // o servidor receba um pedido de conexão do cliente
                    
                    //ATENÇAO... a sequencia de instanciacao dever ser 1o o saida e 2o o entrada
                    saida = new ObjectOutputStream(socket_jogador2.getOutputStream());
                    entrada = new ObjectInputStream(socket_jogador2.getInputStream());
                    System.out.println("Cliente conectado: " + socket_jogador2.getInetAddress().getHostAddress());

                    //para enviar ao jogador 2
                    //saida = new ObjectOutputStream(socket_jogador2.getOutputStream());
                    while (true) {
                        c = (Componente) entrada.readObject();
                        //se for jogador
                        if (c.tipo == Componente.JOGADOR) {
                            //redesenha ou reposiciona o jogador2(cliente) no ambiente do jogador1(servidor)
                            jButtonJogador2.setBounds(c.x, c.y, c.largura, c.altura);
                        } //se for fruta
                        else if (c.tipo == Componente.FRUTA) {
                            jButtonFruta.setBounds(c.x, c.y, c.largura, c.altura);
                        }
                        else if (c.tipo == Componente.PLACAR) { 
                            if (c.idJogador == 2) { 
                                txtPlacarJogador2.setText(String.valueOf(c.pontuacao));
                            }
                            try {
                                saida.writeObject(c);
                                saida.flush();
                            } catch (Exception retransmitE) {
                                System.out.println("Erro ao retransmitir o placar para o Cliente: " + retransmitE.getMessage());
                            }
                        }
                    }
                } catch (Exception e) {
                    System.out.println("Erro: " + e.getMessage());
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJogador1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonJogador2 = new javax.swing.JButton();
        jButtonFruta = new javax.swing.JButton();
        jButtonJogador1 = new javax.swing.JButton();
        txtPlacarJogador1 = new javax.swing.JTextField();
        txtPlacarJogador2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogador 1 - SERVIDOR");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonJogador2.setText("j2");
        jButtonJogador2.setFocusable(false);

        jButtonFruta.setBackground(new java.awt.Color(255, 204, 0));
        jButtonFruta.setText("@");
        jButtonFruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonFrutaKeyPressed(evt);
            }
        });

        jButtonJogador1.setText("j1");
        jButtonJogador1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonJogador2)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButtonJogador1)
                .addGap(37, 37, 37)
                .addComponent(jButtonFruta)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFruta)
                    .addComponent(jButtonJogador1))
                .addGap(58, 58, 58)
                .addComponent(jButtonJogador2)
                .addGap(52, 52, 52))
        );

        txtPlacarJogador1.setEditable(false);
        txtPlacarJogador1.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacarJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacarJogador1ActionPerformed(evt);
            }
        });

        txtPlacarJogador2.setEditable(false);
        txtPlacarJogador2.setBackground(new java.awt.Color(255, 255, 255));
        txtPlacarJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacarJogador2ActionPerformed(evt);
            }
        });

        jLabel4.setText("X");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Placar:");

        javax.swing.GroupLayout jPanelJogador1Layout = new javax.swing.GroupLayout(jPanelJogador1);
        jPanelJogador1.setLayout(jPanelJogador1Layout);
        jPanelJogador1Layout.setHorizontalGroup(
            jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogador1Layout.createSequentialGroup()
                .addGroup(jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJogador1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJogador1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(txtPlacarJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlacarJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJogador1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel3)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelJogador1Layout.setVerticalGroup(
            jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogador1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJogador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPlacarJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(txtPlacarJogador1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int placarJogador1 = 0;
    private final int ID_JOGADOR = 1;
    private void jButtonFrutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonFrutaKeyPressed
        // TODO add your handling code here:

        switch (evt.getKeyCode()) {
            case 37:
                //System.out.println("indo para esquerda");
                Movimenta.irEsquerda(jButtonJogador1);
                break;
            case 38:
                //System.out.println("indo para cima");
                Movimenta.irCima(jButtonJogador1);
                break;
            case 39:
                //System.out.println("indo para direita");
                Movimenta.irDireita(jButtonJogador1, jPanelJogador1.getBounds().width);
                break;
            case 40:
                //System.out.println("indo para baixo");
                Movimenta.irBaixo(jButtonJogador1, jPanelJogador1.getBounds().height);
                break;
        }
        if (Movimenta.pegou(jButtonJogador1, jButtonFruta)) {
            placarJogador1++;
            txtPlacarJogador1.setText(String.valueOf(placarJogador1));
            Movimenta.posicionaAleatorio(jButtonFruta,
                    jPanelJogador1.getBounds().width,
                    jPanelJogador1.getBounds().height);
            try {
                saida.flush();
                c = new Componente(jButtonFruta.getBounds().x,
                        jButtonFruta.getBounds().y,
                        jButtonFruta.getBounds().width,
                        jButtonFruta.getBounds().height);
                c.tipo = Componente.FRUTA;
                Componente cPlacar = new Componente(Componente.PLACAR, placarJogador1, 1);
                saida.writeObject(cPlacar);
                saida.writeObject(c);
            } catch (Exception e) {
                System.out.println("Erro ao enviar a fruta");
            }
        }
        //enviando o botao do jogador1 e o botao da fruta para o cliente
        try {
            saida.flush();
            c = new Componente(jButtonJogador1.getBounds().x,
                    jButtonJogador1.getBounds().y,
                    jButtonJogador1.getBounds().width,
                    jButtonJogador1.getBounds().height);
            c.tipo = Componente.JOGADOR;
            saida.writeObject(c);

        } catch (Exception e) {
            System.out.println("Erro ao enviar jogador1 ao cliente!!");
        }
    }//GEN-LAST:event_jButtonFrutaKeyPressed

    private void txtPlacarJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacarJogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacarJogador1ActionPerformed

    private void txtPlacarJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacarJogador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacarJogador2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorJogador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorJogador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorJogador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorJogador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorJogador1().setVisible(true);
            }
        });
    }
    ServerSocket servidor;
    Socket socket_jogador2;
    ObjectOutputStream saida;
    ObjectInputStream entrada;
    Componente c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFruta;
    private javax.swing.JButton jButtonJogador1;
    private javax.swing.JButton jButtonJogador2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelJogador1;
    private javax.swing.JTextField txtPlacarJogador1;
    private javax.swing.JTextField txtPlacarJogador2;
    // End of variables declaration//GEN-END:variables
}
